# Generated by Django 3.1.1 on 2020-09-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newests',
            name='image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
